# Generated by Django 4.2 on 2023-04-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myname', models.CharField(max_length=32)),
                ('lname', models.CharField(max_length=32)),
                ('no', models.IntegerField()),
                ('email', models.CharField(max_length=323)),
                ('comments', models.CharField(max_length=323)),
                ('company', models.CharField(max_length=323)),
                ('protext', models.TextField()),
                ('indtext', models.TextField()),
            ],
        ),
    ]
