# Generated by Django 4.2 on 2023-05-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeb', '0002_f'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f',
            name='dcollege',
            field=models.TextField(max_length=323),
        ),
        migrations.AlterField(
            model_name='f',
            name='ddegree',
            field=models.TextField(max_length=323),
        ),
        migrations.AlterField(
            model_name='f',
            name='dm1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='f',
            name='dm2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='f',
            name='dmonth',
            field=models.CharField(max_length=323),
        ),
        migrations.AlterField(
            model_name='f',
            name='dpincode',
            field=models.IntegerField(),
        ),
    ]
