# Generated by Django 4.2 on 2023-05-11 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeb', '0004_alter_f_dc1_alter_f_dcc1_alter_f_dcity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='f',
            name='dc1',
        ),
        migrations.RemoveField(
            model_name='f',
            name='dcc1',
        ),
        migrations.RemoveField(
            model_name='f',
            name='dcollege',
        ),
        migrations.RemoveField(
            model_name='f',
            name='dcompany',
        ),
        migrations.RemoveField(
            model_name='f',
            name='ddegree',
        ),
        migrations.RemoveField(
            model_name='f',
            name='dm1',
        ),
        migrations.RemoveField(
            model_name='f',
            name='dm2',
        ),
        migrations.RemoveField(
            model_name='f',
            name='dmonth',
        ),
        migrations.RemoveField(
            model_name='f',
            name='dposition',
        ),
        migrations.RemoveField(
            model_name='f',
            name='dschool',
        ),
    ]
