# Generated by Django 4.2 on 2023-05-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeb', '0006_f_dc1_f_dcc1_f_dcollege_f_dcompany_f_ddegree_f_dm1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f',
            name='dc1',
            field=models.CharField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcc1',
            field=models.CharField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcity',
            field=models.CharField(blank=True, default='aj', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcollege',
            field=models.TextField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcompany',
            field=models.CharField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcountry',
            field=models.CharField(blank=True, default='aj', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='ddegree',
            field=models.TextField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='demail',
            field=models.CharField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='desc',
            field=models.CharField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dm1',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dm2',
            field=models.IntegerField(blank=True, default=8, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dmonth',
            field=models.CharField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dname',
            field=models.CharField(blank=True, default='aj', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dphoneno',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dpincode',
            field=models.IntegerField(blank=True, default=9, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dposition',
            field=models.CharField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dschool',
            field=models.CharField(blank=True, default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dsurname',
            field=models.CharField(blank=True, default='aj', max_length=32, null=True),
        ),
    ]
