# Generated by Django 4.2 on 2023-05-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeb', '0007_alter_f_dc1_alter_f_dcc1_alter_f_dcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f',
            name='dc1',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcc1',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcity',
            field=models.CharField(default='aj', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcollege',
            field=models.TextField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcompany',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dcountry',
            field=models.CharField(default='aj', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='ddegree',
            field=models.TextField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='demail',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='desc',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dm1',
            field=models.IntegerField(default=9, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dm2',
            field=models.IntegerField(default=8, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dmonth',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dname',
            field=models.CharField(default='aj', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dphoneno',
            field=models.IntegerField(default=9, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dpincode',
            field=models.IntegerField(default=9, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dposition',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dschool',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dsurname',
            field=models.CharField(default='aj', max_length=32, null=True),
        ),
    ]
