# Generated by Django 4.2 on 2023-05-13 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumeb', '0008_alter_f_dc1_alter_f_dcc1_alter_f_dcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f',
            name='dm1',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
        migrations.AlterField(
            model_name='f',
            name='dm2',
            field=models.CharField(default='aj', max_length=323, null=True),
        ),
    ]
