# Generated by Django 4.2 on 2023-05-13 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumeb', '0010_checkbox'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkbox',
            old_name='userskils',
            new_name='userskills',
        ),
    ]
